name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List project files
      run: ls -R

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant permission
      run: chmod +x gradlew || true

    - name: Build APK
      run: |
        if [ -f gradlew ]; then
          ./gradlew assembleDebug
        else
          echo "gradlew missing"
          exit 1
        fi
